const config = {
	countries: [
		{id: 'af', name: 'Afghanistan'},
		{id: 'za', name: 'Afrique du Sud'},
		{id: 'ax', name: 'Åland, Îles'},
		{id: 'al', name: 'Albanie'},
		{id: 'dz', name: 'Algérie'},
		{id: 'de', name: 'Allemagne', vatMode: 'ue'},
		{id: 'ad', name: 'Andorre'},
		{id: 'ao', name: 'Angola'},
		{id: 'ai', name: 'Anguilla'},
		{id: 'aq', name: 'Antarctique'},
		{id: 'ag', name: 'Antigua et Barbuda'},
		{id: 'sa', name: 'Arabie Saoudite'},
		{id: 'ar', name: 'Argentine'},
		{id: 'am', name: 'Arménie'},
		{id: 'aw', name: 'Aruba'},
		{id: 'au', name: 'Australie'},
		{id: 'at', name: 'Autriche', vatMode: 'ue'},
		{id: 'az', name: 'Azerbaïdjan'},
		{id: 'bs', name: 'Bahamas'},
		{id: 'bh', name: 'Bahrein'},
		{id: 'bd', name: 'Bangladesh'},
		{id: 'bb', name: 'Barbade'},
		{id: 'by', name: 'Bélarus'},
		{id: 'be', name: 'Belgique', vatMode: 'ue'},
		{id: 'bz', name: 'Bélize'},
		{id: 'bj', name: 'Bénin'},
		{id: 'bm', name: 'Bermudes'},
		{id: 'bt', name: 'Bhoutan'},
		{id: 'bo', name: 'Bolivie'},
		{id: 'bq', name: 'Bonaire, Saint-Eustache et Saba'},
		{id: 'ba', name: 'Bosnie-Herzégovine'},
		{id: 'bw', name: 'Botswana'},
		{id: 'bv', name: 'Bouvet, Ile'},
		{id: 'br', name: 'Brésil'},
		{id: 'bn', name: 'Brunéi Darussalam'},
		{id: 'bg', name: 'Bulgarie', vatMode: 'ue'},
		{id: 'bf', name: 'Burkina Faso'},
		{id: 'bi', name: 'Burundi'},
		{id: 'cv', name: 'Cabo Verde'},
		{id: 'ky', name: 'Caïmans, Iles'},
		{id: 'kh', name: 'Cambodge'},
		{id: 'cm', name: 'Cameroun'},
		{id: 'ca', name: 'Canada'},
		{id: 'cl', name: 'Chili'},
		{id: 'cn', name: 'Chine'},
		{id: 'cx', name: 'Christmas, île'},
		{id: 'cy', name: 'Chypre', vatMode: 'ue'},
		{id: 'cc', name: 'Cocos/Keeling (Îles)'},
		{id: 'co', name: 'Colombie'},
		{id: 'km', name: 'Comores'},
		{id: 'cg', name: 'Congo'},
		{id: 'cd', name: 'Congo, République démocratique du'},
		{id: 'ck', name: 'Cook, Iles'},
		{id: 'kr', name: 'Corée, République de'},
		{id: 'kp', name: 'Corée, République populaire démocratique de'},
		{id: 'cr', name: 'Costa Rica'},
		{id: 'ci', name: 'Côte d\'Ivoire'},
		{id: 'hr', name: 'Croatie', vatMode: 'ue'},
		{id: 'cu', name: 'Cuba'},
		{id: 'cw', name: 'Curaçao'},
		{id: 'dk', name: 'Danemark', vatMode: 'ue'},
		{id: 'dj', name: 'Djibouti'},
		{id: 'do', name: 'Dominicaine, République'},
		{id: 'dm', name: 'Dominique'},
		{id: 'eg', name: 'Egypte'},
		{id: 'sv', name: 'El Salvador'},
		{id: 'ae', name: 'Emirats arabes unis'},
		{id: 'ec', name: 'Equateur'},
		{id: 'er', name: 'Erythrée'},
		{id: 'es', name: 'Espagne', vatMode: 'ue'},
		{id: 'ee', name: 'Estonie', vatMode: 'ue'},
		{id: 'us', name: 'USA'},
		{id: 'et', name: 'Ethiopie'},
		{id: 'fk', name: 'Falkland/Malouines (Îles)'},
		{id: 'fo', name: 'Féroé, îles'},
		{id: 'fj', name: 'Fidji'},
		{id: 'fi', name: 'Finlande', vatMode: 'ue'},
		{id: 'fr', name: 'France', vatMode: 'fr'},
		{id: 'ga', name: 'Gabon'},
		{id: 'gm', name: 'Gambie'},
		{id: 'ge', name: 'Géorgie'},
		{id: 'gs', name: 'Géorgie du sud et les îles Sandwich du sud'},
		{id: 'gh', name: 'Ghana'},
		{id: 'gi', name: 'Gibraltar'},
		{id: 'gr', name: 'Grèce', vatMode: 'ue'},
		{id: 'gd', name: 'Grenade'},
		{id: 'gl', name: 'Groenland'},
		{id: 'gp', name: 'Guadeloupe'},
		{id: 'gu', name: 'Guam'},
		{id: 'gt', name: 'Guatemala'},
		{id: 'gg', name: 'Guernesey'},
		{id: 'gn', name: 'Guinée'},
		{id: 'gw', name: 'Guinée-Bissau'},
		{id: 'gq', name: 'Guinée équatoriale'},
		{id: 'gy', name: 'Guyana'},
		{id: 'gf', name: 'Guyane française'},
		{id: 'ht', name: 'Haïti'},
		{id: 'hm', name: 'Heard, Ile et MacDonald, îles'},
		{id: 'hn', name: 'Honduras'},
		{id: 'hk', name: 'Hong Kong'},
		{id: 'hu', name: 'Hongrie', vatMode: 'ue'},
		{id: 'im', name: 'Île de Man'},
		{id: 'um', name: 'Îles mineures éloignées des Etats-Unis'},
		{id: 'vg', name: 'Îles vierges britanniques'},
		{id: 'vi', name: 'Îles vierges des Etats-Unis'},
		{id: 'in', name: 'Inde'},
		{id: 'io', name: 'Indien (Territoire britannique de l\'océan)'},
		{id: 'id', name: 'Indonésie'},
		{id: 'ir', name: 'Iran, République islamique d\''},
		{id: 'iq', name: 'Iraq'},
		{id: 'ie', name: 'Irlande', vatMode: 'ue'},
		{id: 'is', name: 'Islande'},
		{id: 'il', name: 'Israël'},
		{id: 'it', name: 'Italie', vatMode: 'ue'},
		{id: 'jm', name: 'Jamaïque'},
		{id: 'jp', name: 'Japon'},
		{id: 'je', name: 'Jersey'},
		{id: 'jo', name: 'Jordanie'},
		{id: 'kz', name: 'Kazakhstan'},
		{id: 'ke', name: 'Kenya'},
		{id: 'kg', name: 'Kirghizistan'},
		{id: 'ki', name: 'Kiribati'},
		{id: 'kw', name: 'Koweït'},
		{id: 'la', name: 'Laos'},
		{id: 'ls', name: 'Lesotho'},
		{id: 'lv', name: 'Lettonie', vatMode: 'ue'},
		{id: 'lb', name: 'Liban'},
		{id: 'lr', name: 'Libéria'},
		{id: 'ly', name: 'Libye'},
		{id: 'li', name: 'Liechtenstein'},
		{id: 'lt', name: 'Lituanie', vatMode: 'ue'},
		{id: 'lu', name: 'Luxembourg', vatMode: 'ue'},
		{id: 'mo', name: 'Macao'},
		{id: 'mk', name: 'Macédoine'},
		{id: 'mg', name: 'Madagascar'},
		{id: 'my', name: 'Malaisie'},
		{id: 'mw', name: 'Malawi'},
		{id: 'mv', name: 'Maldives'},
		{id: 'ml', name: 'Mali'},
		{id: 'mt', name: 'Malte', vatMode: 'ue'},
		{id: 'mp', name: 'Mariannes du nord, Iles'},
		{id: 'ma', name: 'Maroc'},
		{id: 'mh', name: 'Marshall, Iles'},
		{id: 'mq', name: 'Martinique'},
		{id: 'mu', name: 'Maurice'},
		{id: 'mr', name: 'Mauritanie'},
		{id: 'yt', name: 'Mayotte'},
		{id: 'mx', name: 'Mexique'},
		{id: 'fm', name: 'Micronésie, Etats Fédérés de'},
		{id: 'md', name: 'Moldova, République de'},
		{id: 'mc', name: 'Monaco'},
		{id: 'mn', name: 'Mongolie'},
		{id: 'me', name: 'Monténégro'},
		{id: 'ms', name: 'Montserrat'},
		{id: 'mz', name: 'Mozambique'},
		{id: 'mm', name: 'Myanmar'},
		{id: 'na', name: 'Namibie'},
		{id: 'nr', name: 'Nauru'},
		{id: 'np', name: 'Népal'},
		{id: 'ni', name: 'Nicaragua'},
		{id: 'ne', name: 'Niger'},
		{id: 'ng', name: 'Nigéria'},
		{id: 'nu', name: 'Niue'},
		{id: 'nf', name: 'Norfolk, Ile'},
		{id: 'no', name: 'Norvège'},
		{id: 'nc', name: 'Nouvelle-Calédonie'},
		{id: 'nz', name: 'Nouvelle-Zélande'},
		{id: 'om', name: 'Oman'},
		{id: 'ug', name: 'Ouganda'},
		{id: 'uz', name: 'Ouzbékistan'},
		{id: 'pk', name: 'Pakistan'},
		{id: 'pw', name: 'Palaos'},
		{id: 'ps', name: 'Palestine, Etat de'},
		{id: 'pa', name: 'Panama'},
		{id: 'pg', name: 'Papouasie-Nouvelle-Guinée'},
		{id: 'py', name: 'Paraguay'},
		{id: 'nl', name: 'Pays-Bas', vatMode: 'ue'},
		{id: 'xx', name: 'Pays inconnu'},
		{id: 'zz', name: 'Pays multiples'},
		{id: 'pe', name: 'Pérou'},
		{id: 'ph', name: 'Philippines'},
		{id: 'pn', name: 'Pitcairn'},
		{id: 'pl', name: 'Pologne', vatMode: 'ue'},
		{id: 'pf', name: 'Polynésie française'},
		{id: 'pr', name: 'Porto Rico'},
		{id: 'pt', name: 'Portugal', vatMode: 'ue'},
		{id: 'qa', name: 'Qatar'},
		{id: 'sy', name: 'République arabe syrienne'},
		{id: 'cf', name: 'République centrafricaine'},
		{id: 're', name: 'Réunion'},
		{id: 'ro', name: 'Roumanie', vatMode: 'ue'},
		{id: 'gb', name: 'Royaume-Uni'},
		{id: 'ru', name: 'Russie, Fédération de'},
		{id: 'rw', name: 'Rwanda'},
		{id: 'eh', name: 'Sahara occidental'},
		{id: 'bl', name: 'Saint-Barthélemy'},
		{id: 'kn', name: 'Saint-Kitts-et-Nevis'},
		{id: 'sm', name: 'Saint-Marin'},
		{id: 'mf', name: 'Saint-Martin (partie française)'},
		{id: 'sx', name: 'Saint-Martin (partie néerlandaise)'},
		{id: 'pm', name: 'Saint-Pierre-et-Miquelon'},
		{id: 'va', name: 'Saint-Siège'},
		{id: 'vc', name: 'Saint-Vincent-et-les-Grenadines'},
		{id: 'sh', name: 'Sainte-Hélène, Ascension et Tristan da Cunha'},
		{id: 'lc', name: 'Sainte-Lucie'},
		{id: 'sb', name: 'Salomon, Iles'},
		{id: 'ws', name: 'Samoa'},
		{id: 'as', name: 'Samoa américaines'},
		{id: 'st', name: 'Sao Tomé-et-Principe'},
		{id: 'sn', name: 'Sénégal'},
		{id: 'rs', name: 'Serbie'},
		{id: 'sc', name: 'Seychelles'},
		{id: 'sl', name: 'Sierra Leone'},
		{id: 'sg', name: 'Singapour'},
		{id: 'sk', name: 'Slovaquie', vatMode: 'ue'},
		{id: 'si', name: 'Slovénie', vatMode: 'ue'},
		{id: 'so', name: 'Somalie'},
		{id: 'sd', name: 'Soudan'},
		{id: 'ss', name: 'Soudan du Sud'},
		{id: 'lk', name: 'Sri Lanka'},
		{id: 'se', name: 'Suède', vatMode: 'ue'},
		{id: 'ch', name: 'Suisse'},
		{id: 'sr', name: 'Suriname'},
		{id: 'sj', name: 'Svalbard et île Jan Mayen'},
		{id: 'sz', name: 'Swaziland'},
		{id: 'tj', name: 'Tadjikistan'},
		{id: 'tw', name: 'Taïwan, Province de Chine'},
		{id: 'tz', name: 'Tanzanie, République unie de'},
		{id: 'td', name: 'Tchad'},
		{id: 'cz', name: 'Tchèque, République', vatMode: 'ue'},
		{id: 'tf', name: 'Terres australes françaises'},
		{id: 'th', name: 'Thaïlande'},
		{id: 'tl', name: 'Timor-Leste'},
		{id: 'tg', name: 'Togo'},
		{id: 'tk', name: 'Tokelau'},
		{id: 'to', name: 'Tonga'},
		{id: 'tt', name: 'Trinité-et-Tobago'},
		{id: 'tn', name: 'Tunisie'},
		{id: 'tm', name: 'Turkménistan'},
		{id: 'tc', name: 'Turks-et-Caïcos (Îles)'},
		{id: 'tr', name: 'Turquie'},
		{id: 'tv', name: 'Tuvalu'},
		{id: 'ua', name: 'Ukraine'},
		{id: 'uy', name: 'Uruguay'},
		{id: 'vu', name: 'Vanuatu'},
		{id: 've', name: 'Venezuela'},
		{id: 'vn', name: 'VietNam'},
		{id: 'wf', name: 'Wallis et Futuna'},
		{id: 'ye', name: 'Yémen'},
		{id: 'zm', name: 'Zambie'},
		{id: 'zw', name: 'Zimbabwe'}
	],
}

export async function getConfig(module=undefined, id=undefined){
	if(module === undefined && id === undefined) return config
	if(module !== undefined && id === undefined) return config[module]
	if(module !== undefined && id !== undefined) return config[module].find(c => c.id === id)
}
